name: way24
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  app_links: ^3.0.1
  cached_network_image: ^3.4.1
  change_app_package_name: ^1.3.0
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  custom_widgets:
    path: "./packages/custom_widgets"
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^2.1.0
  flutter_localizations: 
    sdk: flutter  
  flutter_map: ^7.0.2
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  go_router: ^16.0.0   
  i18n_extension: ^15.0.5  
  intl:
  latlong2: ^0.9.1
  shared_preferences: ^2.4.0
  supabase_flutter: ^2.6.0
  timeline_tile: ^2.0.0
  url_launcher: ^6.3.1
dev_dependencies:
  build_runner: ^2.4.12
  custom_lint:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^3.0.1
  riverpod_lint:
  very_good_analysis: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
